version: '3'
services:
  db:
    image: 'postgres'
    container_name: postgres_db
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/data/db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}